# Docker Compose configuration for CI testing
version: '3.8'

services:
  # PostgreSQL for database compatibility testing
  postgres-13:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: signaldb_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-15:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: signaldb_test
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NATS for messaging backend testing
  nats:
    image: nats:2.10.12
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: ["-js"]
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Test runner service
  signaldb-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      postgres-13:
        condition: service_healthy
      postgres-15:
        condition: service_healthy
      nats:
        condition: service_healthy
    environment:
      - POSTGRES_13_URL=postgres://postgres:postgres@postgres-13:5432/signaldb_test
      - POSTGRES_15_URL=postgres://postgres:postgres@postgres-15:5432/signaldb_test
      - NATS_URL=nats://nats:4222
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    volumes:
      - .:/app
      - /app/target
    working_dir: /app
    command: ["cargo", "test", "--all-features"]

  # Microservices deployment test
  acceptor-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      postgres-15:
        condition: service_healthy
    environment:
      - SIGNALDB_DATABASE_DSN=postgres://postgres:postgres@postgres-15:5432/signaldb_test
      - SIGNALDB_DISCOVERY_DSN=postgres://postgres:postgres@postgres-15:5432/signaldb_test
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - .:/app
      - /app/target
    working_dir: /app
    command: ["cargo", "run", "--bin", "signaldb-acceptor"]

  router-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      postgres-15:
        condition: service_healthy
    environment:
      - SIGNALDB_DATABASE_DSN=postgres://postgres:postgres@postgres-15:5432/signaldb_test
      - SIGNALDB_DISCOVERY_DSN=postgres://postgres:postgres@postgres-15:5432/signaldb_test
    ports:
      - "50053:50053"
      - "3000:3000"
    volumes:
      - .:/app
      - /app/target
    working_dir: /app
    command: ["cargo", "run", "--bin", "signaldb-router"]

  writer-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      postgres-15:
        condition: service_healthy
    environment:
      - SIGNALDB_DATABASE_DSN=postgres://postgres:postgres@postgres-15:5432/signaldb_test
      - SIGNALDB_DISCOVERY_DSN=postgres://postgres:postgres@postgres-15:5432/signaldb_test
    ports:
      - "50051:50051"
    volumes:
      - .:/app
      - /app/target
    working_dir: /app
    command: ["cargo", "run", "--bin", "signaldb-writer"]