//! # Password Hashing and Session Token Utilities
//!
//! Credential hashing for user authentication, complementing the API key
//! hashing in [`crate::auth::Authenticator`].
//!
//! Two different hashing strategies are used deliberately:
//!
//! - **Argon2id for user passwords**: passwords are low-entropy,
//!   human-chosen secrets. A fast hash would allow attackers to brute-force
//!   leaked hashes cheaply, so a memory-hard key derivation function
//!   (Argon2id with per-hash random salts) is required.
//! - **SHA-256 for session tokens (and API keys)**: these are high-entropy
//!   random strings generated by the server. Brute-forcing 256 bits of
//!   randomness is infeasible regardless of hash speed, so a single fast
//!   SHA-256 pass is sufficient and keeps per-request verification cheap.
//!   [`hash_session_token`] mirrors the shape of
//!   `Authenticator::hash_api_key` (SHA-256, lowercase hex) but is kept
//!   self-contained.
//!
//! Session tokens are opaque random strings handed to browsers; only their
//! SHA-256 hash is stored server-side, so a leaked session store does not
//! reveal usable tokens.

use argon2::{
    Argon2,
    password_hash::{
        PasswordHash, PasswordHasher, PasswordVerifier, SaltString, rand_core::OsRng as PhcOsRng,
    },
};
use base64::Engine;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use rand::TryRng;
use sha2::{Digest, Sha256};

/// Prefix for session tokens, making them easy to identify in logs,
/// support tickets, and secret scanners.
pub const SESSION_TOKEN_PREFIX: &str = "sdbs_";

/// Number of random bytes in a session token (before base64 encoding).
const SESSION_TOKEN_BYTES: usize = 32;

/// Errors from password hashing and verification.
#[derive(Debug, thiserror::Error)]
pub enum PasswordError {
    /// Hashing the password failed (e.g. invalid parameters).
    #[error("failed to hash password: {0}")]
    Hash(argon2::password_hash::Error),
    /// The stored hash is not a valid PHC string.
    #[error("malformed password hash: {0}")]
    MalformedHash(argon2::password_hash::Error),
}

/// Hash a user password with Argon2id using default parameters and a
/// fresh random salt.
///
/// Returns a PHC-format string (e.g. `$argon2id$v=19$m=19456,t=2,p=1$...`)
/// that embeds the algorithm, parameters, salt, and digest, suitable for
/// storage and later verification with [`verify_password`].
///
/// # Errors
///
/// Returns [`PasswordError::Hash`] if the underlying hasher fails.
pub fn hash_password(password: &str) -> Result<String, PasswordError> {
    let salt = SaltString::generate(&mut PhcOsRng);
    let hash = Argon2::default()
        .hash_password(password.as_bytes(), &salt)
        .map_err(PasswordError::Hash)?;
    Ok(hash.to_string())
}

/// Verify a user password against a stored PHC-format Argon2 hash.
///
/// Returns `Ok(true)` if the password matches, `Ok(false)` if it does not.
///
/// # Errors
///
/// Returns [`PasswordError::MalformedHash`] only if `phc_hash` is not a
/// valid PHC string — a mismatched password is not an error.
pub fn verify_password(password: &str, phc_hash: &str) -> Result<bool, PasswordError> {
    let parsed = PasswordHash::new(phc_hash).map_err(PasswordError::MalformedHash)?;
    match Argon2::default().verify_password(password.as_bytes(), &parsed) {
        Ok(()) => Ok(true),
        Err(argon2::password_hash::Error::Password) => Ok(false),
        Err(e) => Err(PasswordError::MalformedHash(e)),
    }
}

/// Generate a new opaque session token: [`SESSION_TOKEN_PREFIX`] followed
/// by 32 bytes of OS randomness encoded as URL-safe base64 without padding.
///
/// The raw token is returned to the client (e.g. in a cookie); only its
/// [`hash_session_token`] digest should be stored server-side.
///
/// # Panics
///
/// Panics if the operating system's random number generator fails.
/// This is intentional: silently producing a predictable token would be a
/// security vulnerability, and OS RNG failure is not recoverable here.
pub fn generate_session_token() -> String {
    let mut bytes = [0u8; SESSION_TOKEN_BYTES];
    if let Err(error) = rand::rngs::SysRng.try_fill_bytes(&mut bytes) {
        panic!("OS random number generator failed while generating session token: {error}");
    }
    let encoded = URL_SAFE_NO_PAD.encode(bytes);
    format!("{SESSION_TOKEN_PREFIX}{encoded}")
}

/// Hash a session token with SHA-256, returning lowercase hex.
///
/// Deterministic, so the stored digest can be looked up directly by
/// hashing an incoming token. Same shape as `Authenticator::hash_api_key`.
pub fn hash_session_token(token: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(token.as_bytes());
    hex::encode(hasher.finalize())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn hash_password_round_trip_verifies_correct_password() {
        let hash = hash_password("correct horse battery staple").unwrap();
        assert!(verify_password("correct horse battery staple", &hash).unwrap());
    }

    #[test]
    fn verify_password_returns_false_for_wrong_password() {
        let hash = hash_password("correct horse battery staple").unwrap();
        assert!(!verify_password("Tr0ub4dor&3", &hash).unwrap());
    }

    #[test]
    fn hash_password_produces_unique_hashes_that_both_verify() {
        let hash1 = hash_password("same password").unwrap();
        let hash2 = hash_password("same password").unwrap();
        assert_ne!(hash1, hash2, "random salts must differ");
        assert!(verify_password("same password", &hash1).unwrap());
        assert!(verify_password("same password", &hash2).unwrap());
    }

    #[test]
    fn verify_password_returns_error_for_garbage_hash() {
        assert!(verify_password("anything", "not-a-phc-string").is_err());
    }

    #[test]
    fn hash_password_output_is_phc_argon2id() {
        let hash = hash_password("some password").unwrap();
        assert!(hash.starts_with("$argon2id$"));
        // Must parse as a PHC string
        PasswordHash::new(&hash).unwrap();
    }

    #[test]
    fn generate_session_token_has_prefix_and_decodes_to_32_bytes() {
        let token = generate_session_token();
        assert!(token.starts_with(SESSION_TOKEN_PREFIX));
        let raw = URL_SAFE_NO_PAD
            .decode(&token[SESSION_TOKEN_PREFIX.len()..])
            .unwrap();
        assert_eq!(raw.len(), SESSION_TOKEN_BYTES);
    }

    #[test]
    fn generate_session_token_is_unique_across_generations() {
        let tokens: HashSet<String> = (0..100).map(|_| generate_session_token()).collect();
        assert_eq!(tokens.len(), 100);
    }

    #[test]
    fn hash_session_token_is_deterministic_hex_sha256() {
        let token = generate_session_token();
        let hash1 = hash_session_token(&token);
        let hash2 = hash_session_token(&token);
        assert_eq!(hash1, hash2);
        assert_eq!(hash1.len(), 64);
        assert!(hash1.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn hash_session_token_differs_between_tokens() {
        let hash1 = hash_session_token(&generate_session_token());
        let hash2 = hash_session_token(&generate_session_token());
        assert_ne!(hash1, hash2);
    }
}
