[package]
name = "acceptor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow-schema.workspace = true
parquet.workspace = true

opentelemetry-proto.workspace = true
tonic.workspace = true
