[package]
name = "acceptor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow-flight.workspace = true
arrow-schema.workspace = true
parquet.workspace = true

opentelemetry-proto.workspace = true
tonic.workspace = true

tracing.workspace = true

tokio.workspace = true
futures.workspace = true

log.workspace = true
anyhow.workspace = true

axum.workspace = true
