pub mod admin;
pub mod api_error;
pub mod flight;
mod flight_decode;
pub mod logql;
pub mod management;
pub mod oauth;
pub mod ops;
pub mod promql;
pub mod pyroscope;
pub mod query;
pub mod session;
pub mod tempo;
pub mod tenant;
