[package]
name = "querier"
version = "0.3.0"
edition.workspace = true
license.workspace = true

[dependencies]
common = { path = "../common" }
logql = { path = "../logql" }
traceql-parser = { path = "../traceql" }
tempo-api = { path = "../tempo-api", features = ["server"] }

async-trait.workspace = true
chrono.workspace = true
regex = "1"
dashmap.workspace = true
hex.workspace = true

anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
datafusion.workspace = true
tracing.workspace = true
opentelemetry.workspace = true
tonic.workspace = true
arrow-flight.workspace = true
object_store.workspace = true
futures.workspace = true
bytes.workspace = true
url.workspace = true
serde.workspace = true
serde_json.workspace = true
iceberg-rust.workspace = true
datafusion_iceberg.workspace = true

thiserror.workspace = true
promql-parser.workspace = true

# PromQL support

[dev-dependencies]
common = { path = "../common", features = ["testing"] }
tracing-subscriber.workspace = true
tracing-opentelemetry.workspace = true
opentelemetry_sdk = { workspace = true, features = ["trace", "testing"] }
