[package]
name = "querier"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
common = { path = "../common" }
messaging = { path = "../messaging" }
tempo-api = { path = "../tempo-api", features = ["server"] }

async-trait.workspace = true

axum = { workspace = true, features = ["macros"] }
tower-http = { workspace = true, features = ["trace"] }
anyhow.workspace = true
tokio.workspace = true
log.workspace = true
datafusion.workspace = true
object_store.workspace = true
serde_json.workspace = true
tracing.workspace = true
tonic.workspace = true

thiserror.workspace = true
