[package]
name = "querier"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common = { path = "../common" }
tempo-api = { path = "../tempo-api" }

async-trait.workspace = true

axum = { workspace = true, features = ["macros"] }
tower-http = { workspace = true, features = ["trace"] }
anyhow.workspace = true
tower.workspace = true
tokio.workspace = true
log.workspace = true
datafusion.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
