#!/usr/bin/env python3
"""Render SignalDB's OpenTelemetry telemetry-schema files for the docs site.

Every instrumentation scope SignalDB emits carries
``schema_url: <base>/<version>`` (see ``otel/registry/manifest.yaml`` and
``common::self_monitoring::SIGNALDB_SCHEMA_URL``). This script writes one
telemetry-schema file (OTel schema ``file_format`` 1.1.0) per released
version at exactly that path under the site directory, so the URL resolves.

Inputs, all already maintained by release-please:

- the manifest's top-level ``schema_url`` gives the base URL and the current
  version;
- ``src/common/CHANGELOG.md`` headings (``## [X.Y.Z]``) give the release
  history — the ``common`` crate and the manifest are bumped in lockstep.

Usage: render-schema-files.py <manifest.yaml> <CHANGELOG.md> <site-dir>
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# The first release whose telemetry carried the docs-site schema URL. Older
# versions never referenced these files, so they are not published.
FIRST_PUBLISHED = (0, 2, 1)

HEADING = re.compile(r"^## \[(\d+)\.(\d+)\.(\d+)\]", re.MULTILINE)


def parse_version(text: str) -> tuple[int, int, int]:
    major, minor, patch = text.split(".")
    return int(major), int(minor), int(patch)


def fmt(v: tuple[int, int, int]) -> str:
    return ".".join(str(part) for part in v)


def manifest_schema_url(manifest: Path) -> tuple[str, tuple[int, int, int]]:
    for line in manifest.read_text().splitlines():
        if line.startswith("schema_url:"):
            url = line.split(":", 1)[1].strip()
            base, _, version = url.rpartition("/")
            return base, parse_version(version)
    raise SystemExit(f"{manifest}: no top-level schema_url")


def released_versions(changelog: Path) -> list[tuple[int, int, int]]:
    return sorted({(int(a), int(b), int(c)) for a, b, c in HEADING.findall(changelog.read_text())})


def schema_file(base: str, version: tuple[int, int, int], history: list[tuple[int, int, int]]) -> str:
    lines = [
        "# SignalDB telemetry schema (OpenTelemetry schema file format 1.1.0).",
        "# Generated by scripts/render-schema-files.py from otel/registry/manifest.yaml",
        "# and src/common/CHANGELOG.md; the registry itself lives at",
        "# https://github.com/cedricziel/signaldb/tree/main/otel/registry",
        "file_format: 1.1.0",
        f"schema_url: {base}/{fmt(version)}",
        "versions:",
    ]
    for v in sorted((v for v in history if v <= version), reverse=True):
        lines.append(f"  {fmt(v)}:")
    return "\n".join(lines) + "\n"


def index_html(base: str, versions: list[tuple[int, int, int]]) -> str:
    items = "\n".join(
        f'    <li><a href="{base}/{fmt(v)}">{fmt(v)}</a></li>' for v in sorted(versions, reverse=True)
    )
    return (
        "<!doctype html><meta charset=\"utf-8\"><title>SignalDB telemetry schemas</title>\n"
        "<h1>SignalDB telemetry schemas</h1>\n"
        "<p>OpenTelemetry schema files referenced by the <code>schema_url</code> on SignalDB's\n"
        "instrumentation scopes. Source registry:\n"
        '<a href="https://github.com/cedricziel/signaldb/tree/main/otel/registry">otel/registry</a>.</p>\n'
        f"<ul>\n{items}\n</ul>\n"
    )


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2
    manifest, changelog, site = (Path(a) for a in argv[1:])
    base, current = manifest_schema_url(manifest)
    history = released_versions(changelog)
    if current not in history:
        # A release PR that bumped the manifest but not (yet) the changelog
        # can't happen — release-please writes both — but be defensive.
        history.append(current)
    published = [v for v in history if v >= FIRST_PUBLISHED]
    out = site / "schemas"
    out.mkdir(parents=True, exist_ok=True)
    for v in published:
        (out / fmt(v)).write_text(schema_file(base, v, history))
    (out / "index.html").write_text(index_html(base, published))
    print(f"rendered {len(published)} schema file(s) under {out} (current {fmt(current)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
