use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};

#[derive(Parser)]
#[command(name = "xtask", about = "SignalDB code generation tooling")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Generate code from the OpenAPI spec
    Generate,
    /// Check that generated code is up-to-date (for CI)
    Check,
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Command::Generate => generate(false),
        Command::Check => generate(true),
    }
}

fn project_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask must be inside the workspace")
        .to_path_buf()
}

fn generate(check_only: bool) -> Result<()> {
    let root = project_root();
    // The spec itself is emitted from the router's code-first annotations by the
    // golden test in `router::openapi` (UPDATE_OPENAPI=1 cargo test -p router).
    // xtask consumes that committed spec to generate the downstream clients.
    let spec_json = std::fs::read_to_string(root.join("api/signaldb-api.json"))
        .context("reading api/signaldb-api.json (run UPDATE_OPENAPI=1 cargo test -p router)")?;
    let json_value: serde_json::Value =
        serde_json::from_str(&spec_json).context("parsing api/signaldb-api.json")?;

    // --- signaldb-sdk client (progenitor) ---
    let sdk_client = generate_sdk_client(&json_value)?;
    write_or_check(
        &root.join("src/signaldb-sdk/src/generated.rs"),
        &sdk_client,
        check_only,
    )?;

    if check_only {
        eprintln!("All generated files are up-to-date.");
    } else {
        eprintln!("Code generation complete.");
    }
    Ok(())
}

/// Generate a full HTTP client from the OpenAPI spec using progenitor.
///
/// The spec is emitted by utoipa as OpenAPI 3.1, but progenitor parses via the
/// `openapiv3` crate, which targets 3.0. The only incompatibility our schemas
/// hit is 3.1's nullable encoding (`"type": ["string", "null"]`), so we
/// downconvert those to 3.0's `"type": "string", "nullable": true` before
/// handing the spec to progenitor. The served spec and the checked-in
/// `signaldb-api.json` stay 3.1; this rewrite is progenitor-input only.
fn generate_sdk_client(spec: &serde_json::Value) -> Result<String> {
    let mut spec = spec.clone();
    downconvert_nullable_types(&mut spec);
    // progenitor/openapiv3 only accept a 3.0.x version string.
    if let Some(obj) = spec.as_object_mut() {
        obj.insert(
            "openapi".to_string(),
            serde_json::Value::String("3.0.3".to_string()),
        );
    }
    let openapi: openapiv3::OpenAPI =
        serde_json::from_value(spec).context("parsing spec as openapiv3::OpenAPI")?;

    let mut settings = progenitor::GenerationSettings::default();
    settings
        .with_interface(progenitor::InterfaceStyle::Builder)
        .with_tag(progenitor::TagStyle::Merged);

    let mut generator = progenitor::Generator::new(&settings);
    let tokens = generator
        .generate_tokens(&openapi)
        .context("progenitor generate_tokens")?;
    let ast: syn::File = syn::parse2(tokens).context("parsing progenitor output as syn::File")?;
    let code = prettyplease::unparse(&ast);

    let formatted = run_rustfmt(&code)?;
    Ok(format!(
        "// This file is generated by `cargo xtask generate`. Do not edit.\n\n{formatted}"
    ))
}

/// Recursively rewrite OpenAPI 3.1 nullable type arrays into the 3.0 form that
/// the `openapiv3` crate (and thus progenitor) understands:
/// `"type": ["string", "null"]` becomes `"type": "string", "nullable": true`,
/// and a single-element `"type": ["string"]` is unwrapped to `"type": "string"`.
fn downconvert_nullable_types(value: &mut serde_json::Value) {
    match value {
        serde_json::Value::Object(map) => {
            if let Some(serde_json::Value::Array(types)) = map.get("type") {
                let mut non_null: Vec<String> = Vec::new();
                let mut has_null = false;
                for t in types {
                    match t.as_str() {
                        Some("null") => has_null = true,
                        Some(other) => non_null.push(other.to_string()),
                        None => {}
                    }
                }
                if non_null.len() == 1 {
                    map.insert(
                        "type".to_string(),
                        serde_json::Value::String(non_null.remove(0)),
                    );
                    if has_null {
                        map.insert("nullable".to_string(), serde_json::Value::Bool(true));
                    }
                }
            }
            for v in map.values_mut() {
                downconvert_nullable_types(v);
            }
        }
        serde_json::Value::Array(arr) => {
            for v in arr {
                downconvert_nullable_types(v);
            }
        }
        _ => {}
    }
}

/// Run `rustfmt` on a Rust source string, returning the formatted output.
fn run_rustfmt(code: &str) -> Result<String> {
    use std::io::Write;
    use std::process::{Command, Stdio};

    let mut child = Command::new("rustfmt")
        .arg("--edition")
        .arg("2024")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .context("spawning rustfmt (is it installed?)")?;

    child
        .stdin
        .take()
        .context("opening rustfmt stdin")?
        .write_all(code.as_bytes())
        .context("writing to rustfmt stdin")?;

    let output = child.wait_with_output().context("waiting for rustfmt")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("rustfmt failed: {stderr}");
    }

    String::from_utf8(output.stdout).context("rustfmt produced non-UTF-8 output")
}

/// Write content to a file, or in check mode, verify the file matches.
fn write_or_check(path: &Path, content: &str, check_only: bool) -> Result<()> {
    let rel = path.strip_prefix(project_root()).unwrap_or(path).display();

    if check_only {
        let existing = std::fs::read_to_string(path)
            .with_context(|| format!("reading {rel} (does it exist?)"))?;
        if existing != content {
            anyhow::bail!(
                "Generated code is out of date: {rel}\nRun `cargo xtask generate` to update."
            );
        }
        eprintln!("  OK  {rel}");
    } else {
        std::fs::write(path, content).with_context(|| format!("writing {rel}"))?;
        eprintln!("  GEN {rel}");
    }
    Ok(())
}
