// This file is generated by `cargo xtask generate`. Do not edit.

/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
///Standard API error response
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Standard API error response",
///  "type": "object",
///  "required": [
///    "error",
///    "message"
///  ],
///  "properties": {
///    "error": {
///      "description": "Error category",
///      "type": "string"
///    },
///    "message": {
///      "description": "Human-readable error description",
///      "type": "string"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct ApiError {
    ///Error category
    pub error: ::std::string::String,
    ///Human-readable error description
    pub message: ::std::string::String,
}
impl ::std::convert::From<&ApiError> for ApiError {
    fn from(value: &ApiError) -> Self {
        value.clone()
    }
}
///API key information (without the raw key)
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "API key information (without the raw key)",
///  "type": "object",
///  "required": [
///    "created_at",
///    "id"
///  ],
///  "properties": {
///    "created_at": {
///      "description": "ISO 8601 creation timestamp",
///      "type": "string"
///    },
///    "id": {
///      "description": "Unique key identifier",
///      "type": "string"
///    },
///    "name": {
///      "description": "Optional human-readable name",
///      "type": "string"
///    },
///    "revoked_at": {
///      "description": "ISO 8601 revocation timestamp (if revoked)",
///      "type": "string"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct ApiKeyResponse {
    ///ISO 8601 creation timestamp
    pub created_at: ::std::string::String,
    ///Unique key identifier
    pub id: ::std::string::String,
    ///Optional human-readable name
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub name: ::std::option::Option<::std::string::String>,
    ///ISO 8601 revocation timestamp (if revoked)
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub revoked_at: ::std::option::Option<::std::string::String>,
}
impl ::std::convert::From<&ApiKeyResponse> for ApiKeyResponse {
    fn from(value: &ApiKeyResponse) -> Self {
        value.clone()
    }
}
///Request body for creating a new API key
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Request body for creating a new API key",
///  "type": "object",
///  "properties": {
///    "name": {
///      "description": "Optional human-readable name for the key",
///      "type": "string"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct CreateApiKeyRequest {
    ///Optional human-readable name for the key
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub name: ::std::option::Option<::std::string::String>,
}
impl ::std::convert::From<&CreateApiKeyRequest> for CreateApiKeyRequest {
    fn from(value: &CreateApiKeyRequest) -> Self {
        value.clone()
    }
}
impl ::std::default::Default for CreateApiKeyRequest {
    fn default() -> Self {
        Self {
            name: Default::default(),
        }
    }
}
///Response returned when a new API key is created (includes the raw key)
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Response returned when a new API key is created (includes the raw key)",
///  "type": "object",
///  "required": [
///    "created_at",
///    "id",
///    "key"
///  ],
///  "properties": {
///    "created_at": {
///      "description": "ISO 8601 creation timestamp",
///      "type": "string"
///    },
///    "id": {
///      "description": "Unique key identifier",
///      "type": "string"
///    },
///    "key": {
///      "description": "The raw API key (only shown once at creation time)",
///      "type": "string"
///    },
///    "name": {
///      "description": "Optional human-readable name",
///      "type": "string"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct CreateApiKeyResponse {
    ///ISO 8601 creation timestamp
    pub created_at: ::std::string::String,
    ///Unique key identifier
    pub id: ::std::string::String,
    ///The raw API key (only shown once at creation time)
    pub key: ::std::string::String,
    ///Optional human-readable name
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub name: ::std::option::Option<::std::string::String>,
}
impl ::std::convert::From<&CreateApiKeyResponse> for CreateApiKeyResponse {
    fn from(value: &CreateApiKeyResponse) -> Self {
        value.clone()
    }
}
///Request body for creating a new dataset
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Request body for creating a new dataset",
///  "type": "object",
///  "required": [
///    "name"
///  ],
///  "properties": {
///    "name": {
///      "description": "Dataset name",
///      "type": "string"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct CreateDatasetRequest {
    ///Dataset name
    pub name: ::std::string::String,
}
impl ::std::convert::From<&CreateDatasetRequest> for CreateDatasetRequest {
    fn from(value: &CreateDatasetRequest) -> Self {
        value.clone()
    }
}
///Request body for creating a new tenant
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Request body for creating a new tenant",
///  "type": "object",
///  "required": [
///    "id",
///    "name"
///  ],
///  "properties": {
///    "default_dataset": {
///      "description": "Default dataset name",
///      "type": "string"
///    },
///    "id": {
///      "description": "Unique tenant identifier",
///      "type": "string"
///    },
///    "name": {
///      "description": "Human-readable tenant name",
///      "type": "string"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct CreateTenantRequest {
    ///Default dataset name
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub default_dataset: ::std::option::Option<::std::string::String>,
    ///Unique tenant identifier
    pub id: ::std::string::String,
    ///Human-readable tenant name
    pub name: ::std::string::String,
}
impl ::std::convert::From<&CreateTenantRequest> for CreateTenantRequest {
    fn from(value: &CreateTenantRequest) -> Self {
        value.clone()
    }
}
///Dataset information returned by the API
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Dataset information returned by the API",
///  "type": "object",
///  "required": [
///    "created_at",
///    "id",
///    "name",
///    "tenant_id"
///  ],
///  "properties": {
///    "created_at": {
///      "description": "ISO 8601 creation timestamp",
///      "type": "string"
///    },
///    "id": {
///      "description": "Unique dataset identifier",
///      "type": "string"
///    },
///    "name": {
///      "description": "Dataset name",
///      "type": "string"
///    },
///    "tenant_id": {
///      "description": "Tenant that owns this dataset",
///      "type": "string"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatasetResponse {
    ///ISO 8601 creation timestamp
    pub created_at: ::std::string::String,
    ///Unique dataset identifier
    pub id: ::std::string::String,
    ///Dataset name
    pub name: ::std::string::String,
    ///Tenant that owns this dataset
    pub tenant_id: ::std::string::String,
}
impl ::std::convert::From<&DatasetResponse> for DatasetResponse {
    fn from(value: &DatasetResponse) -> Self {
        value.clone()
    }
}
///Response containing a list of API keys
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Response containing a list of API keys",
///  "type": "object",
///  "required": [
///    "api_keys"
///  ],
///  "properties": {
///    "api_keys": {
///      "description": "List of API key records (without raw keys)",
///      "type": "array",
///      "items": {
///        "$ref": "#/definitions/ApiKeyResponse"
///      }
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct ListApiKeysResponse {
    ///List of API key records (without raw keys)
    pub api_keys: ::std::vec::Vec<ApiKeyResponse>,
}
impl ::std::convert::From<&ListApiKeysResponse> for ListApiKeysResponse {
    fn from(value: &ListApiKeysResponse) -> Self {
        value.clone()
    }
}
///Response containing a list of datasets
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Response containing a list of datasets",
///  "type": "object",
///  "required": [
///    "datasets"
///  ],
///  "properties": {
///    "datasets": {
///      "description": "List of dataset records",
///      "type": "array",
///      "items": {
///        "$ref": "#/definitions/DatasetResponse"
///      }
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct ListDatasetsResponse {
    ///List of dataset records
    pub datasets: ::std::vec::Vec<DatasetResponse>,
}
impl ::std::convert::From<&ListDatasetsResponse> for ListDatasetsResponse {
    fn from(value: &ListDatasetsResponse) -> Self {
        value.clone()
    }
}
///Response containing a list of tenants
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Response containing a list of tenants",
///  "type": "object",
///  "required": [
///    "tenants"
///  ],
///  "properties": {
///    "tenants": {
///      "description": "List of tenant records",
///      "type": "array",
///      "items": {
///        "$ref": "#/definitions/TenantResponse"
///      }
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct ListTenantsResponse {
    ///List of tenant records
    pub tenants: ::std::vec::Vec<TenantResponse>,
}
impl ::std::convert::From<&ListTenantsResponse> for ListTenantsResponse {
    fn from(value: &ListTenantsResponse) -> Self {
        value.clone()
    }
}
///Tenant information returned by the API
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Tenant information returned by the API",
///  "type": "object",
///  "required": [
///    "created_at",
///    "id",
///    "name",
///    "source",
///    "updated_at"
///  ],
///  "properties": {
///    "created_at": {
///      "description": "ISO 8601 creation timestamp",
///      "type": "string"
///    },
///    "default_dataset": {
///      "description": "Default dataset name",
///      "type": "string"
///    },
///    "id": {
///      "description": "Unique tenant identifier",
///      "type": "string"
///    },
///    "name": {
///      "description": "Human-readable tenant name",
///      "type": "string"
///    },
///    "source": {
///      "description": "Source of the tenant record (config or database)",
///      "type": "string"
///    },
///    "updated_at": {
///      "description": "ISO 8601 last-updated timestamp",
///      "type": "string"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct TenantResponse {
    ///ISO 8601 creation timestamp
    pub created_at: ::std::string::String,
    ///Default dataset name
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub default_dataset: ::std::option::Option<::std::string::String>,
    ///Unique tenant identifier
    pub id: ::std::string::String,
    ///Human-readable tenant name
    pub name: ::std::string::String,
    ///Source of the tenant record (config or database)
    pub source: ::std::string::String,
    ///ISO 8601 last-updated timestamp
    pub updated_at: ::std::string::String,
}
impl ::std::convert::From<&TenantResponse> for TenantResponse {
    fn from(value: &TenantResponse) -> Self {
        value.clone()
    }
}
///Request body for updating an existing tenant
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Request body for updating an existing tenant",
///  "type": "object",
///  "properties": {
///    "default_dataset": {
///      "description": "Updated default dataset",
///      "type": "string"
///    },
///    "name": {
///      "description": "Updated tenant name",
///      "type": "string"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct UpdateTenantRequest {
    ///Updated default dataset
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub default_dataset: ::std::option::Option<::std::string::String>,
    ///Updated tenant name
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub name: ::std::option::Option<::std::string::String>,
}
impl ::std::convert::From<&UpdateTenantRequest> for UpdateTenantRequest {
    fn from(value: &UpdateTenantRequest) -> Self {
        value.clone()
    }
}
impl ::std::default::Default for UpdateTenantRequest {
    fn default() -> Self {
        Self {
            default_dataset: Default::default(),
            name: Default::default(),
        }
    }
}
