[package]
name = "pyroscope-api"
version = "0.1.3"
edition = "2024"
description = "Pyroscope-compatible API types"
license = "AGPL-3.0"

[dependencies]
serde.workspace = true
serde_json.workspace = true
utoipa.workspace = true
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[package.metadata.cargo-machete]
# workspace-hack is managed by `cargo hakari` (see workspace-hack/README.md)
ignored = ["workspace-hack"]
