name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: short # Changed from 1 to short for better performance
  CARGO_INCREMENTAL: 0 # Disable incremental compilation for CI
  CARGO_NET_RETRY: 10

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Fast preliminary checks - fail fast strategy
  check:
    name: Check & Lint
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - uses: actions/checkout@v4

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
          cache: true

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "check"
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Cargo check
        run: cargo check --all-targets --all-features

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      # Cache compiled dependencies for other jobs
      - name: Compress target for sharing
        run: tar -czf target-deps.tar.gz target/

      - name: Upload target artifact
        uses: actions/upload-artifact@v4
        with:
          name: target-deps-${{ github.run_id }}
          path: target-deps.tar.gz
          retention-days: 1

  # Parallel test matrix - depends on check passing
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: check
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, 1.82.0] # Consolidated MSRV test
        database: [postgresql, sqlite]
        exclude:
          # Only test MSRV with sqlite to reduce matrix size
          - rust: 1.82.0
            database: postgresql
          - rust: beta
            database: sqlite # Reduce redundant testing

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: signaldb_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          cache: true

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "test-${{ matrix.rust }}-${{ matrix.database }}"
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      # Download pre-compiled dependencies
      - name: Download target artifact
        uses: actions/download-artifact@v4
        with:
          name: target-deps-${{ github.run_id }}

      - name: Extract target directory
        run: tar -xzf target-deps.tar.gz

      - name: Configure database environment
        run: |
          mkdir -p .data
          if [ "${{ matrix.database }}" = "postgresql" ]; then
            echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/signaldb_test" >> $GITHUB_ENV
            echo "SIGNALDB_DATABASE_DSN=postgres://postgres:postgres@localhost:5432/signaldb_test" >> $GITHUB_ENV
          else
            echo "DATABASE_URL=sqlite://.data/test.db" >> $GITHUB_ENV
            echo "SIGNALDB_DATABASE_DSN=sqlite://.data/test.db" >> $GITHUB_ENV
          fi

      - name: Run all tests
        run: |
          cargo test --workspace --all-features
        env:
          RUST_LOG: warn # Reduced log level for faster tests

  # Build jobs - only run after tests pass
  build-binaries:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    needs: [check, test]
    strategy:
      matrix:
        include:
          # Reduced matrix - only build what you actually deploy
          - os: ubuntu-latest
            deployment: monolithic
          - os: ubuntu-latest
            deployment: microservices
          # Only add macOS if you actually need macOS binaries
          - os: macos-latest
            deployment: monolithic

    steps:
      - uses: actions/checkout@v4

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "security"

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build-${{ matrix.os }}"
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install system dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install protobuf

      - name: Build binaries
        run: |
          if [ "${{ matrix.deployment }}" = "monolithic" ]; then
            cargo build --release --bin signaldb
          else
            cargo build --release -p acceptor --bin signaldb-acceptor
            cargo build --release -p router --bin signaldb-router
            cargo build --release -p writer --bin signaldb-writer
          fi

      - name: Test binary execution
        run: |
          if [ "${{ matrix.deployment }}" = "monolithic" ]; then
            ./target/release/signaldb --help
          else
            ./target/release/signaldb-acceptor --help || echo "Acceptor help test"
            ./target/release/signaldb-router --help || echo "Router help test"
            ./target/release/signaldb-writer --help || echo "Writer help test"
          fi

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}-${{ matrix.deployment }}
          path: target/release/signaldb*
          retention-days: 7

  # Lightweight deployment test - only essential combinations
  deployment-test:
    name: Deployment Test
    runs-on: ubuntu-latest
    needs: build-binaries
    strategy:
      matrix:
        # Reduced matrix - test key combinations only
        include:
          - database: postgresql
            deployment: monolithic
          - database: sqlite
            deployment: microservices

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: signaldb_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries-ubuntu-latest-${{ matrix.deployment }}
          path: target/release/

      - name: Make binaries executable
        run: chmod +x target/release/signaldb*

      - name: Configure environment
        run: |
          mkdir -p .data
          if [ "${{ matrix.database }}" = "postgresql" ]; then
            echo "SIGNALDB_DATABASE_DSN=postgres://postgres:postgres@localhost:5432/signaldb_test" >> $GITHUB_ENV
            echo "SIGNALDB_DISCOVERY_DSN=postgres://postgres:postgres@localhost:5432/signaldb_test" >> $GITHUB_ENV
          else
            echo "SIGNALDB_DATABASE_DSN=sqlite://.data/test_deployment.db" >> $GITHUB_ENV
            echo "SIGNALDB_DISCOVERY_DSN=sqlite://.data/test_deployment.db" >> $GITHUB_ENV
          fi

      - name: Test deployment
        run: |
          if [ "${{ matrix.deployment }}" = "monolithic" ]; then
            timeout 5s ./target/release/signaldb || echo "Monolithic test completed"
          else
            timeout 3s ./target/release/signaldb-acceptor &
            timeout 3s ./target/release/signaldb-router &
            timeout 3s ./target/release/signaldb-writer &
            wait
            echo "Microservices test completed"
          fi

  # Security and coverage jobs - run in parallel with tests
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v4

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true

      - name: Install security tools
        run: |
          cargo install cargo-audit cargo-deny

      - name: Run security audit
        run: cargo audit

      - name: Run cargo deny
        run: cargo deny check

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: check
    # Only run coverage on main branch or when specifically requested
    if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'coverage')

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: signaldb_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: llvm-tools-preview
          cache: true

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "coverage"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov

      - name: Setup environment
        run: |
          mkdir -p .data
          echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/signaldb_test" >> $GITHUB_ENV
          echo "SIGNALDB_DATABASE_DSN=postgres://postgres:postgres@localhost:5432/signaldb_test" >> $GITHUB_ENV

      - name: Generate coverage report
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          fail_ci_if_error: false
