name: Grafana Plugin - API Compatibility Check

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]
    paths:
      - 'src/grafana-plugin/**'
      - '.github/workflows/grafana-plugin-is-compatible*.yml'

jobs:
  compatibility:
    name: Grafana API Compatibility
    uses: ./.github/workflows/grafana-plugin-is-compatible-reusable.yml
